/*
Copyright 2018 Hasura.io

*/

// This file was automatically generated by lister-gen

package v1alpha1

// RemoteListerExpansion allows custom methods to be added to
// RemoteLister.
type RemoteListerExpansion interface{}

// RemoteNamespaceListerExpansion allows custom methods to be added to
// RemoteNamespaceLister.
type RemoteNamespaceListerExpansion interface{}
