/*
Copyright 2018 Hasura.io

*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/hasura/gitkube/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Remotes returns a RemoteInformer.
	Remotes() RemoteInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// Remotes returns a RemoteInformer.
func (v *version) Remotes() RemoteInformer {
	return &remoteInformer{factory: v.SharedInformerFactory}
}
